export const quizData =[{
    id:1,
    question:'Что является самым важным?',
    answer1:{
        text: 'Строгость и аккуратность во всем',
        JavaScript: 0,
        CPP: 3,
        Java: 3,
        Golang: 2,
        Python: 0,
        Haskell: 0,
        Elixir: 0,
    },
    answer2:{
        text:'Полная свобода действий',
        JavaScript: 3,
        CPP: 0,
        Java: 0,
        Golang: 0,
        Python: 1,
        Haskell: 0,
        Elixir: 0,
    },
    answer3: {
        text: 'Гибкость, там где она необходима',
        JavaScript: 0,
        CPP: 0,
        Java: 0,
        Golang: 0,
        Python: 3,
        Haskell: 0,
        Elixir: 0,
    },
    answer4:{ text:'Сложность, дающая эффективность',
        JavaScript: 0,
        CPP: 2,
        Java: 0,
        Golang: 0,
        Python: 0,
        Haskell: 3,
        Elixir: 3,
    },
},
    {
        id: 2,
        question: 'Как ты относишься к работе с памятью?',
        answer1: {
            text:'Память ?! Это что вообще такое?',
            JavaScript: 2,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 1,
            Haskell: 0,
            Elixir: 0,
        },
        answer2: {
            text:'Максимально контролирую',
            JavaScript: 0,
            CPP: 3,
            Java: 0,
            Golang: 0,
            Python: 0,
            Haskell: 0,
            Elixir: 0,
        },
        answer3: {
            text:'У меня есть помощник, который делает работает с ней',
            JavaScript: 0,
            CPP: 0,
            Java: 3,
            Golang: 3,
            Python: 2,
            Haskell: 3,
            Elixir: 3,
        },
        answer4: {
            text:'Мы с ней редко пересекаемся, поэтому с опаской',
            JavaScript: 3,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 0,
            Haskell: 0,
            Elixir: 0,
        },
    },
    {
        id: 3,
        question: 'Какой стиль самый лучший ?',
        answer1: {
            text:'camelCase',
            JavaScript: 3,
            CPP: 0,
            Java: 2,
            Golang: 3,
            Python: 0,
            Haskell: 2,
            Elixir: 0,
        },
        answer2: {
            text:'kebab-case',
            JavaScript: 0,
            CPP: 3,
            Java: 0,
            Golang: 0,
            Python: 0,
            Haskell: 0,
            Elixir: 0,
        },
        answer3: {
            text:'snake_case',
            JavaScript: 0,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 3,
            Haskell: 0,
            Elixir: 2,
        },
        answer4: {
            text:'Все, смешиваю их, выбирая, по настроению',
            JavaScript: 1,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 0,
            Haskell: 0,
            Elixir: 0,
        }
    },
    {
        id: 4,
        question: 'Опиши себя прилагательным',
        answer1: {
            text:'Квадратный',
            JavaScript: 0,
            CPP: 0,
            Java: 3,
            Golang: 2,
            Python: 0,
            Haskell: 0,
            Elixir: 0,
        },
        answer2: {
            text:'Бесформенный',
            JavaScript: 3,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 2,
            Haskell: 0,
            Elixir: 0,
        },
        answer3: {
            text:'Сложный',
            JavaScript: 0,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 0,
            Haskell: 3,
            Elixir: 3,
        },
        answer4: {
            text:'Быстрый',
            JavaScript: 0,
            CPP: 3,
            Java: 0,
            Golang: 1,
            Python: 0,
            Haskell: 2,
            Elixir: 2,
        },
    },
    {
        id: 5,
        question: 'Выбери что круче',
        answer1: {
            text:'Многопоточность',
            JavaScript: 0,
            CPP: 3,
            Java: 3,
            Golang: 5,
            Python: 0,
            Haskell: 0,
            Elixir: 0,
        },
        answer2: {
            text:'Ассинхронность',
            JavaScript: 3,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 3,
            Haskell: 0,
            Elixir: 0,
        },
        answer3: {
            text:'Компактность',
            JavaScript: 0,
            CPP: 3,
            Java: 0,
            Golang: 0,
            Python: 0,
            Haskell: 2,
            Elixir: 2,
        },
        answer4: {
            text:'Экспрессивность',
            JavaScript: 0,
            CPP: 0,
            Java: 0,
            Golang: 0,
            Python: 0,
            Haskell: 3,
            Elixir: 3,
        },
    }];
export const langs = {
    JavaScript:{ name: 'JavaScript',
        value: 0 },

    CPP:{ name: 'CPP',
        value: 0 },

    Java:{ name: 'Java',
        value: 0 },

    Golang:{ name: 'Golang',
        value: 0 },

    Python:{ name: 'Python',
        value: 0 },

    Haskell:{ name: 'Haskell',
        value: 0 },

    Elixir:{ name: 'Elixir',
        value: 0 },
};

export const RESULT_DIVIDER = '|';